### ISSUE TITLE
.class files instead of .java files

### ISSUE THREAD

**Issue by Nakuls426** [therajatrai/Data-Structures-Algorithms#1]
You have uploaded **_.class_** extension files instead of **_java_**. The class file is consists of bytecode. Which humans cant understand. Like the one in the image below.
 
![2021-05-14](https://user-images.githubusercontent.com/28592882/118305552-c042cf80-b505-11eb-8772-073ffb45a9b8.png)

**Comment by therajatrai** [comment]
Reviewed and Sorted
